2014-10-25 13:55:00,121 manager INFO 1.1.0
2014-10-25 13:55:00,121 manager INFO Copyright (C) 2003-2010
2014-10-25 13:55:00,121 manager INFO   Noriaki Ando
2014-10-25 13:55:00,121 manager INFO   Intelligent Systems Research Institute, AIST
2014-10-25 13:55:00,121 manager INFO Manager starting.
2014-10-25 13:55:00,122 manager INFO Starting local logging.
2014-10-25 13:55:00,142 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2014-10-25 13:55:02,153 ManagerServant INFO Master manager not found
2014-10-25 13:55:02,154 manager ERROR Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\OpenRTM_aist\Manager.py", line 1751, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2014-10-25 13:55:03,650 SdoServiceAdmin WARNING No available SDO service in the factory: 
2014-10-25 13:55:03,650 SdoServiceAdmin ERROR type  already exists.
2014-10-25 13:55:03,651 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2014-10-25 13:55:03,653 SdoServiceAdmin ERROR type 7311f968-ad8a-4e08-bbfd-fb19b89c31bc already exists.
2014-10-25 13:55:06,890 DataBase ERROR interface matched with old descriptor: port.DataBase::mDataBase.database
2014-10-25 14:11:14,721 DataBase ERROR interface matched with old descriptor: port.DataBase::mDataBase.database
